
DECLARE

	A number(10);
	B number(10);
	C number(10);

BEGIN
	A :=&NUMBER1;
	B:=&NUMBER2;
	C:=&NUMBER3;

	IF A>B AND A>C THEN
		DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS'||A);
	ELSIF B>A AND B>C THEN
		DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS'||B);
	ELSE
		DBMS_OUTPUT.PUT_LINE('GREATEST NUMBER IS'||C);
	END IF;
END;
/